package EngineeringEducationDatabase

type RouterGroup struct {
	ProfessionalConstructionDatabaseRouter
	TalentTrainingDatabaseRouter
	SocialServiceDatabaseRouter
	ConditionalGuaranteeDatabaseRouter
	SubjectConstructionDatabaseRouter
	PolicyDatabaseRouter
	InternationalExchangeDatabaseRouter
	BasicInfomationDatabaseRouter
}
