package EngineeringEducationDatabase

type ServiceGroup struct {
	ProfessionalConstructionDatabaseService
	TalentTrainingDatabaseService
	SocialServiceDatabaseService
	ConditionalGuaranteeDatabaseService
	SubjectConstructionDatabaseService
	PolicyDatabaseService
	InternationalExchangeDatabaseService
	BasicInfomationDatabaseService
}
